### ISSUE TITLE
Module-level self reference 

### ISSUE THREAD

**Issue by skoslowski** [procitec/sphinx-test-spec#1]
This feels not very idiomatic. What's the reasoning/benefit?

https://github.com/procitec/sphinx-test-spec/blob/c0c38c83509c90fef53cd65fa570db004cbc2f49/sphinx_test_spec/directives.py#L14

**Comment by kreuzberger** [comment]
A pattern i often use to have python module level variables to be easily accessed in all module functions
see e.g. https://stackoverflow.com/questions/1977362/how-to-create-module-wide-variables-in-python/1978076#1978076

Same as from here [How to crate module wide variables](https://designcorral.com/questions/how-to-create-module-wide-variables-in-python/ ) with Answer 2

Or from here: https://stackoverflow.com/questions/1429814/how-to-programmatically-set-a-global-module-variable

The reason for this is sad, but true: Not nowing better to get a "this" instance in python module level programming :-)

**Comment by skoslowski** [comment]
Thanks. Still not sure quite why you need that reference. Let's discuss this elsewhere...

**Comment by kreuzberger** [comment]
Fixed "internal" state handling by using domains specific data from sphinx.

```
test_domain = self.env.get_domain("test")
_state = test_domain.data["state"]

```
